language: python
python:
  - '2.7'

before_install:
  - sudo apt-get update
  - curl -L http://bootstrap.saltstack.org | sudo sh -s -- git develop

install:
  - sudo mkdir -p /srv && sudo ln -sfn $PWD /srv/formula
  # See what kind of travis box you're on
  # to help with making your states compatible with travis
  - sudo salt-call grains.items --local

script:
  - sudo salt-call state.show_highstate --local --retcode-passthrough --config-dir=test/etc
  - sudo salt-call state.highstate --local --retcode-passthrough --config-dir=test/etc
