language: python
python:
  - '2.7'

env:
  global:
    - BS_PIP_ALLOWED=1
    - BS_ECHO_DEBUG=1
  matrix:
    - STATE=rsyncd
    - STATE=rsyncd.config

before_install:
  - sudo apt-get update
  - curl -L http://bootstrap.saltstack.org | sudo -E sh -s -- stable

install:
  - sudo mkdir -p /srv && sudo ln -sfn $PWD /srv/formula
  # See what kind of travis box you're on to help with making your states
  # compatible with travis
  - sudo salt-call grains.items --local

script:
  - sudo salt-call state.show_sls $STATE --local --retcode-passthrough --config-dir=test/etc
  - sudo salt-call state.sls $STATE --local --retcode-passthrough --config-dir=test/etc

  # For debugging purpose
  - cat /etc/default/rsync
  - test -f /etc/rsyncd.conf && cat /etc/rsyncd.conf || echo "No rsyncd.conf"

  # Idempotence check
  - sudo salt-call state.sls $STATE --local --retcode-passthrough --config-dir=test/etc > /tmp/second
  - cat /tmp/second
  - bash -c '! grep -q "^Not Run:" /tmp/second'
